[package]
name = "lenovo"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A placeholder."
homepage = "https://github.com/lenovo-it/lenovo"
repository = "https://github.com/lenovo-it/lenovo"
readme = "README.md"
